"""Phase 06: media engine (MAD-001 §24-27, §56; TDD-001 §50, §88, §92, §124-125; PRD-001 §18-19, §25-30).

Unit tests cover the structured argument builders, probe parsing and validation
logic without a system FFmpeg (an injectable runner stands in). Integration
tests exercise the real FFmpeg/FFprobe binaries and are skipped when FFmpeg is
unavailable. Source media is generated by the Phase05 mock providers.
"""
from __future__ import annotations

import asyncio
import json
import shutil
from pathlib import Path

import pytest

from api.core.errors import MediaProcessingError
from api.domain.enums import ProductionMode
from api.domain.outputs import ShortSegment
from api.domain.production import ProductionConfig
from api.media import (
    FFmpegMediaEngine,
    MASTER_PROFILE,
    SHORT_PROFILE,
    MediaEngine,
    MediaExpectations,
    MediaProbe,
    MediaValidationResult,
    OverlaySpec,
    RenderProfile,
    RenderRequest,
    VisualizerInput,
    build_render_args,
    master_render_profile,
    probe_to_model,
    radio_overlay_pixels,
    run_validation_checks,
    short_render_profile,
    visualizer_region_pixels,
)
from api.media.ffmpeg import _escape_filter, _run_process

TEST_PROFILE = RenderProfile(
    name="test",
    width=320,
    height=180,
    fps=10,
    video_codec="libx264",
    audio_codec="aac",
    crf=30,
    preset="ultrafast",
)

FFMPEG_PRESENT = shutil.which("ffmpeg") is not None and shutil.which("ffprobe") is not None


# --- Render profiles (MAD-001 §56) -------------------------------------------

def test_master_profile_matches_mad_defaults():
    assert (MASTER_PROFILE.width, MASTER_PROFILE.height) == (1920, 1080)
    assert MASTER_PROFILE.fps == 30
    assert MASTER_PROFILE.video_codec == "libx264"
    assert MASTER_PROFILE.audio_codec == "aac"


def test_short_profile_is_vertical():
    assert (SHORT_PROFILE.width, SHORT_PROFILE.height) == (1080, 1920)


def test_render_profile_defaults():
    profile = RenderProfile(name="p", width=640, height=360)
    assert profile.fps == 30
    assert profile.crf == 23
    assert profile.pixel_format == "yuv420p"


# --- Structured argument builder (TDD-001 §92) --------------------------------

def _request(tmp_path, **kwargs) -> RenderRequest:
    defaults = dict(
        background=tmp_path / "bg.png",
        audio=tmp_path / "a.wav",
        output_path=tmp_path / "out.mp4",
    )
    defaults.update(kwargs)
    return RenderRequest(**defaults)


def test_render_args_are_a_structured_list(tmp_path):
    args = build_render_args(_request(tmp_path), TEST_PROFILE)
    assert isinstance(args, list)
    assert all(isinstance(a, str) for a in args)


def test_render_args_baseline_structure(tmp_path):
    args = build_render_args(_request(tmp_path), TEST_PROFILE)
    assert args[0] == "-y"
    assert "-i" in args
    assert "-filter_complex" in args
    assert "-map" in args and "[vout]" in args and "1:a" in args
    assert "-c:v" in args and "libx264" in args
    assert "-c:a" in args and "aac" in args
    assert "-shortest" in args
    assert args[-1] == str(tmp_path / "out.mp4")


def test_render_args_include_background_and_audio_inputs(tmp_path):
    args = build_render_args(_request(tmp_path), TEST_PROFILE)
    assert args[args.index("-i") + 1] == str(tmp_path / "bg.png")
    assert str(tmp_path / "a.wav") in args


def test_render_args_include_overlay_inputs(tmp_path):
    request = _request(tmp_path, overlays=[OverlaySpec(path=tmp_path / "r.png")])
    args = build_render_args(request, TEST_PROFILE)
    assert str(tmp_path / "r.png") in args
    # background=0, audio=1, overlay=2 -> filter graph references [2:v]
    assert "[2:v]" in args[args.index("-filter_complex") + 1]


def test_render_args_segment_trims_only_audio(tmp_path):
    request = _request(
        tmp_path,
        segment=ShortSegment(start_seconds=3.5, duration_seconds=5.0),
    )
    args = build_render_args(request, TEST_PROFILE)
    audio_pos = args.index(str(tmp_path / "a.wav"))
    assert args[audio_pos - 5 : audio_pos - 3] == ["-ss", "3.5"]
    assert args[audio_pos - 3 : audio_pos - 1] == ["-t", "5"]


def test_filter_graph_background_scales_and_pads(tmp_path):
    graph = build_render_args(_request(tmp_path), TEST_PROFILE)[
        build_render_args(_request(tmp_path), TEST_PROFILE).index("-filter_complex") + 1
    ]
    assert f"scale=320:180:force_original_aspect_ratio=decrease" in graph
    assert f"pad=320:180" in graph
    assert graph.rstrip().endswith("[vout]")


def test_filter_graph_overlay_uses_null_relabel_when_untransformed(tmp_path):
    request = _request(tmp_path, overlays=[OverlaySpec(path=tmp_path / "r.png", x=10, y=20)])
    graph = build_render_args(request, TEST_PROFILE)[
        build_render_args(request, TEST_PROFILE).index("-filter_complex") + 1
    ]
    assert "[2:v]null[ovsrc0]" in graph
    assert "[base][ovsrc0]overlay=10:20" in graph


def test_filter_graph_overlay_opacity_and_scale(tmp_path):
    request = _request(
        tmp_path,
        overlays=[OverlaySpec(path=tmp_path / "r.png", width=100, height=100, opacity=0.5)],
    )
    graph = build_render_args(request, TEST_PROFILE)[
        build_render_args(request, TEST_PROFILE).index("-filter_complex") + 1
    ]
    assert "colorchannelmixer=aa=0.50" in graph
    assert "[ovsrc0]scale=100:100" in graph


def test_filter_graph_branding_drawtext(tmp_path):
    request = _request(
        tmp_path,
        branding_text="MY:CHANNEL",
        branding_font=tmp_path / "font.ttf",
    )
    graph = build_render_args(request, TEST_PROFILE)[
        build_render_args(request, TEST_PROFILE).index("-filter_complex") + 1
    ]
    assert "drawtext=text='MY\\:CHANNEL'" in graph
    assert "fontfile=" in graph


def test_filter_graph_branding_opacity_adds_alpha(tmp_path):
    request = _request(
        tmp_path,
        branding_text="MY",
        branding_font=tmp_path / "font.ttf",
        branding_opacity=0.65,
    )
    graph = build_render_args(request, TEST_PROFILE)[
        build_render_args(request, TEST_PROFILE).index("-filter_complex") + 1
    ]
    assert "fontcolor=white:alpha=0.65" in graph


def test_filter_graph_branding_align_center_anchors_on_midpoint(tmp_path):
    """TDD-001 §128: center branding drops the pixel x for ``(w-text_w)/2`` so the
    text hugs the frame midpoint regardless of length."""
    request = _request(
        tmp_path,
        branding_text="MY",
        branding_font=tmp_path / "font.ttf",
        branding_align="center",
        branding_y=1728,
    )
    graph = build_render_args(request, TEST_PROFILE)[
        build_render_args(request, TEST_PROFILE).index("-filter_complex") + 1
    ]
    assert "x=(w-text_w)/2" in graph
    assert "y=1728" in graph
    assert "fontcolor=white" in graph


def test_render_args_short_trims_audio_and_centers_branding(tmp_path):
    """Phase 16: a 9:16 short trims only the audio input to the segment, keeps
    the visualizer input, and renders the frame at the short profile size."""
    request = _request(
        tmp_path,
        overlays=[OverlaySpec(path=tmp_path / "r.png")],
        visualizer=_viz_input(tmp_path),
        branding_text="MY",
        branding_font=tmp_path / "font.ttf",
        branding_align="center",
        segment=ShortSegment(start_seconds=10.0, duration_seconds=15.0),
    )
    args = build_render_args(request, SHORT_PROFILE)
    audio_pos = args.index(str(tmp_path / "a.wav"))
    assert args[audio_pos - 5 : audio_pos - 3] == ["-ss", "10"]
    assert args[audio_pos - 3 : audio_pos - 1] == ["-t", "15"]
    graph = args[args.index("-filter_complex") + 1]
    assert "x=(w-text_w)/2" in graph
    assert f"scale={SHORT_PROFILE.width}:{SHORT_PROFILE.height}" in graph
    assert "drawtext=" in graph


# --- Visualizer compositing (TDD-001 §52) -------------------------------------

def _viz_input(tmp_path, **kwargs) -> VisualizerInput:
    defaults = dict(
        frames_dir=tmp_path / "viz",
        fps=30,
        region_x=10,
        region_y=20,
        region_width=40,
        region_height=40,
        duration_seconds=2.0,
    )
    defaults.update(kwargs)
    return VisualizerInput(**defaults)


def test_render_args_add_visualizer_sequence_input(tmp_path):
    request = _request(
        tmp_path,
        overlays=[OverlaySpec(path=tmp_path / "radio.png")],
        visualizer=_viz_input(tmp_path),
    )
    args = build_render_args(request, TEST_PROFILE)
    pattern = str(tmp_path / "viz" / "%05d.png")
    assert pattern in args
    # ["-loop", "1", "-framerate", "30", "-i", "<pattern>"] — looped to audio end
    assert args[args.index(pattern) - 5 : args.index(pattern) + 1] == [
        "-loop", "1", "-framerate", "30", "-i", pattern,
    ]


def test_filter_graph_composites_visualizer_into_region(tmp_path):
    request = _request(
        tmp_path,
        overlays=[OverlaySpec(path=tmp_path / "radio.png")],
        visualizer=_viz_input(tmp_path),
    )
    graph = build_render_args(request, TEST_PROFILE)[
        build_render_args(request, TEST_PROFILE).index("-filter_complex") + 1
    ]
    # bg=0, audio=1, radio=2, visualizer=3 -> scaled to the region, then overlaid
    assert "[3:v]format=rgba,scale=40:40[viz3]" in graph
    assert "overlay=10:20:enable='between(t,0,2)'" in graph


def test_filter_graph_visualizer_precedes_branding(tmp_path):
    request = _request(
        tmp_path,
        visualizer=_viz_input(tmp_path),
        branding_text="MY",
        branding_font=tmp_path / "font.ttf",
    )
    graph = build_render_args(request, TEST_PROFILE)[
        build_render_args(request, TEST_PROFILE).index("-filter_complex") + 1
    ]
    assert "overlay=10:20" in graph
    assert "drawtext=" in graph
    assert graph.rstrip().endswith("[vout]")


def test_render_args_without_visualizer_have_no_framerate_input(tmp_path):
    args = build_render_args(_request(tmp_path), TEST_PROFILE)
    assert "-framerate" not in args


# --- Render profile from production config (MAD-001 §56, PRD-001 §27) ---------

def test_master_render_profile_honors_production_dimensions():
    config = ProductionConfig(
        mode=ProductionMode.GENRE,
        genre="lofi",
        master_width=1280,
        master_height=720,
        fps=24,
    )
    profile = master_render_profile(config)
    assert (profile.width, profile.height) == (1280, 720)
    assert profile.fps == 24
    # encoding defaults stay externalized through the base profile
    assert profile.video_codec == MASTER_PROFILE.video_codec
    assert profile.audio_codec == MASTER_PROFILE.audio_codec
    assert profile.crf == MASTER_PROFILE.crf


def test_master_render_profile_defaults_without_config():
    assert master_render_profile(None) is MASTER_PROFILE


def test_short_render_profile_honors_production_dimensions():
    config = ProductionConfig(
        mode=ProductionMode.GENRE,
        genre="lofi",
        short_width=720,
        short_height=1280,
        fps=24,
    )
    profile = short_render_profile(config)
    assert (profile.width, profile.height) == (720, 1280)
    assert profile.fps == 24
    # encoding defaults stay externalized through the base profile
    assert profile.video_codec == SHORT_PROFILE.video_codec
    assert profile.audio_codec == SHORT_PROFILE.audio_codec
    assert profile.crf == SHORT_PROFILE.crf


def test_short_render_profile_defaults_without_config():
    assert short_render_profile(None) is SHORT_PROFILE


# --- Probe parsing (ffprobe JSON) --------------------------------------------

SAMPLE_PROBE_JSON = {
    "format": {"format_name": "mov,mp4,m4a", "duration": "15.4"},
    "streams": [
        {"codec_type": "video", "codec_name": "h264", "width": 320, "height": 180,
         "avg_frame_rate": "30000/1001"},
        {"codec_type": "audio", "codec_name": "aac", "sample_rate": "22050",
         "channels": 2, "bit_rate": "128000"},
    ],
}


def test_probe_to_model_parses_streams():
    probe = probe_to_model(SAMPLE_PROBE_JSON)
    assert probe.has_video and probe.has_audio
    assert probe.width == 320 and probe.height == 180
    assert abs(probe.fps - 29.97) < 0.01
    assert probe.audio_codec == "aac"
    assert probe.sample_rate == 22050
    assert probe.channels == 2
    assert abs(probe.duration_seconds - 15.4) < 0.01
    assert probe.container_format == "mov,mp4,m4a"


def test_probe_to_model_audio_only():
    probe = probe_to_model({"format": {"format_name": "wav"}, "streams": [
        {"codec_type": "audio", "codec_name": "pcm_s16le", "sample_rate": "44100", "channels": 1},
    ]})
    assert probe.has_audio and not probe.has_video
    assert probe.video_codec is None
    assert probe.sample_rate == 44100


# --- Validation checks (PRD-001 §18) ------------------------------------------

def _probe(**overrides) -> MediaProbe:
    base = dict(duration_seconds=15.0, sample_rate=22050, channels=1,
                audio_codec="pcm_s16le", video_codec="h264", width=320,
                height=180, fps=10.0, has_audio=True, has_video=True)
    base.update(overrides)
    return MediaProbe(**base)


def test_validation_passes_all_checks():
    result = run_validation_checks(
        _probe(),
        MediaExpectations(require_video=True, width=320, height=180, fps=10,
                          min_sample_rate=20000, min_channels=1,
                          audio_codec="pcm_s16le", video_codec="h264"),
        exists=True,
    )
    assert result.valid is True
    assert result.checks


def test_validation_fails_on_resolution_mismatch():
    result = run_validation_checks(
        _probe(width=640, height=360),
        MediaExpectations(require_video=True, width=320, height=180),
        exists=True,
    )
    assert result.valid is False
    assert "resolution" in [c.name for c in result.failures]


def test_validation_fails_when_audio_missing():
    result = run_validation_checks(_probe(has_audio=False), MediaExpectations(), exists=True)
    assert result.valid is False
    assert "audio_present" in [c.name for c in result.failures]


def test_validation_rejects_missing_file():
    result = run_validation_checks(MediaProbe(), MediaExpectations(), exists=False)
    assert result.valid is False
    assert result.failures[0].name == "exists"


# --- FFmpegMediaEngine with a fake runner (unit) ------------------------------

class FakeRunner:
    def __init__(self, ffprobe_json=None, error: Exception | None = None):
        self.calls: list[list[str]] = []
        self.ffprobe_json = ffprobe_json
        self.error = error

    async def __call__(self, cmd, *, timeout=None):
        self.calls.append(cmd)
        if self.error:
            raise self.error
        if self.ffprobe_json is not None:
            return json.dumps(self.ffprobe_json).encode(), b""
        return b"", b""


@pytest.fixture
def engine(tmp_path) -> FFmpegMediaEngine:
    return FFmpegMediaEngine(ffmpeg_bin="ffmpeg-test", ffprobe_bin="ffprobe-test")


def test_ffmpeg_engine_conforms_to_media_engine_protocol():
    assert isinstance(FFmpegMediaEngine(), MediaEngine)


async def test_render_master_runs_ffmpeg_and_returns_output(tmp_path):
    runner = FakeRunner()
    engine = FFmpegMediaEngine(runner=runner)
    output = tmp_path / "nested" / "out.mp4"
    request = _request(tmp_path, output_path=output)
    result = await engine.render_master(request, profile=TEST_PROFILE)
    assert result == output
    assert output.parent.is_dir()
    cmd = runner.calls[0]
    assert cmd[0] == "ffmpeg"
    assert "render" not in cmd  # no shell wrapper
    assert cmd[-1] == str(output)


async def test_render_short_uses_short_profile_default(tmp_path):
    runner = FakeRunner()
    engine = FFmpegMediaEngine(runner=runner)
    await engine.render_short(_request(tmp_path))
    cmd = runner.calls[0]
    assert "1920" in " ".join(cmd)  # SHORT_PROFILE height is 1920


async def test_analyze_audio_uses_ffprobe_and_parses_json(tmp_path):
    path = tmp_path / "a.wav"
    path.write_bytes(b"\x00" * 10)
    runner = FakeRunner(ffprobe_json=SAMPLE_PROBE_JSON)
    engine = FFmpegMediaEngine(runner=runner)
    probe = await engine.analyze_audio(path)
    assert probe.sample_rate == 22050
    assert runner.calls[0][0] == "ffprobe"
    assert "-print_format" in runner.calls[0]


async def test_validate_media_missing_file_short_circuits(tmp_path):
    runner = FakeRunner()
    engine = FFmpegMediaEngine(runner=runner)
    result = await engine.validate_media(tmp_path / "missing.mp4")
    assert result.valid is False
    assert result.failures[0].name == "exists"
    assert runner.calls == []  # no subprocess was invoked


async def test_validate_media_surfaces_probe_error(tmp_path):
    path = tmp_path / "broken.mp4"
    path.write_bytes(b"not media")
    runner = FakeRunner(error=MediaProcessingError("probe boom"))
    engine = FFmpegMediaEngine(runner=runner)
    result = await engine.validate_media(path)
    assert result.valid is False
    assert result.failures[0].name == "readable"


async def test_extract_audio_builds_vn_command(tmp_path):
    runner = FakeRunner()
    engine = FFmpegMediaEngine(runner=runner)
    src = tmp_path / "src.mp4"
    src.write_bytes(b"x")
    out = tmp_path / "audio.wav"
    result = await engine.extract_audio(src, out)
    assert result == out
    cmd = runner.calls[0]
    assert "-vn" in cmd
    assert "-acodec" in cmd and "pcm_s16le" in cmd
    assert cmd[-1] == str(out)


async def test_extract_segment_builds_ss_t_command(tmp_path):
    runner = FakeRunner()
    engine = FFmpegMediaEngine(runner=runner)
    src = tmp_path / "src.wav"
    src.write_bytes(b"x")
    out = tmp_path / "seg.wav"
    result = await engine.extract_segment(src, out, start=2.0, duration=4.0)
    assert result == out
    cmd = runner.calls[0]
    assert cmd[cmd.index("-ss") + 1] == "2"
    assert cmd[cmd.index("-t") + 1] == "4"


async def test_provider_error_propagates(tmp_path):
    runner = FakeRunner(error=MediaProcessingError("boom"))
    engine = FFmpegMediaEngine(runner=runner)
    with pytest.raises(MediaProcessingError):
        await engine.render_master(_request(tmp_path), profile=TEST_PROFILE)


# --- Real FFmpeg integration (skipped when FFmpeg is absent) ------------------

@pytest.fixture
def media_sources(tmp_path):
    """Real WAV + PNG generated by the Phase05 mock providers."""
    from api.capabilities import ImageGenerationRequest, MusicGenerationRequest
    from api.providers.mock import MockImageProvider, MockMusicProvider

    wav = tmp_path / "master.wav"
    wav.write_bytes(
        asyncio.run(
            MockMusicProvider(sample_rate=22050).generate(
                MusicGenerationRequest(prompt="lofi", duration_seconds=15)
            )
        ).audio_bytes
    )
    bg = tmp_path / "bg.png"
    bg.write_bytes(
        asyncio.run(
            MockImageProvider().generate(
                ImageGenerationRequest(prompt="bg", width=320, height=180)
            )
        ).image_bytes
    )
    radio = tmp_path / "radio.png"
    radio.write_bytes(
        asyncio.run(
            MockImageProvider().generate(
                ImageGenerationRequest(prompt="radio", width=100, height=100)
            )
        ).image_bytes
    )
    return {"wav": wav, "bg": bg, "radio": radio, "tmp": tmp_path}


@pytest.mark.skipif(not FFMPEG_PRESENT, reason="FFmpeg/FFprobe not on PATH")
async def test_integration_render_master_and_validate(media_sources):
    engine = FFmpegMediaEngine()
    out = media_sources["tmp"] / "master.mp4"
    await engine.render_master(
        RenderRequest(
            background=media_sources["bg"],
            audio=media_sources["wav"],
            output_path=out,
        ),
        profile=TEST_PROFILE,
    )
    probe = await engine.analyze_audio(out)
    assert probe.has_video and probe.has_audio
    assert (probe.width, probe.height) == (320, 180)
    assert probe.video_codec == "h264"
    assert probe.audio_codec == "aac"
    assert abs(probe.duration_seconds - 15.0) < 2.0

    result = await engine.validate_media(
        out,
        expectations=MediaExpectations(
            require_video=True,
            width=320,
            height=180,
            fps=10,
            audio_codec="aac",
            video_codec="h264",
        ),
    )
    assert result.valid is True


@pytest.mark.skipif(not FFMPEG_PRESENT, reason="FFmpeg/FFprobe not on PATH")
async def test_integration_render_master_with_visualizer_radio_and_branding(media_sources):
    """Phase 15: background + radio + visualizer sprites + branding + audio."""
    from api.domain.audio import AudioAnalysis
    from api.media import VisualizerEngine

    engine = FFmpegMediaEngine()
    viz_engine = VisualizerEngine()
    data = await viz_engine.generate_data(
        AudioAnalysis(duration_seconds=15.0), master_path=media_sources["wav"]
    )
    layout = viz_engine.render(data).layout
    rx, ry, rw, rh = radio_overlay_pixels(layout, width=TEST_PROFILE.width, height=TEST_PROFILE.height)
    vx, vy, vw, vh = visualizer_region_pixels(layout, width=TEST_PROFILE.width, height=TEST_PROFILE.height)

    frames_dir = media_sources["tmp"] / "vizframes"
    frames_dir.mkdir(parents=True, exist_ok=True)
    for index, sprite in enumerate(viz_engine.render_frames(data, width=vw, height=vh), start=1):
        (frames_dir / f"{index:05d}.png").write_bytes(sprite)

    arial = Path("C:/Windows/Fonts/arial.ttf")
    out = media_sources["tmp"] / "master-viz.mp4"
    await engine.render_master(
        RenderRequest(
            background=media_sources["bg"],
            audio=media_sources["wav"],
            overlays=[
                OverlaySpec(
                    path=media_sources["radio"],
                    x=rx,
                    y=ry,
                    width=rw,
                    height=rh,
                    opacity=0.85,
                )
            ],
            visualizer=VisualizerInput(
                frames_dir=frames_dir,
                fps=data.fps,
                region_x=vx,
                region_y=vy,
                region_width=vw,
                region_height=vh,
                duration_seconds=data.timestamps[-1] + 1.0 / data.fps,
            ),
            branding_text="MY CHANNEL",
            branding_font=arial if arial.is_file() else None,
            branding_x=4,
            branding_y=4,
            branding_size=12,
            output_path=out,
        ),
        profile=TEST_PROFILE,
    )
    probe = await engine.analyze_audio(out)
    assert probe.has_video and probe.has_audio
    assert (probe.width, probe.height) == (320, 180)
    result = await engine.validate_media(
        out,
        expectations=MediaExpectations(
            require_video=True, width=320, height=180, fps=10, audio_codec="aac"
        ),
    )
    assert result.valid is True


@pytest.mark.skipif(not FFMPEG_PRESENT, reason="FFmpeg/FFprobe not on PATH")
async def test_integration_render_short_with_overlay_and_branding(media_sources):
    engine = FFmpegMediaEngine()
    arial = Path("C:/Windows/Fonts/arial.ttf")
    out = media_sources["tmp"] / "short.mp4"
    request = RenderRequest(
        background=media_sources["bg"],
        audio=media_sources["wav"],
        overlays=[OverlaySpec(path=media_sources["radio"], x=110, y=40, width=100, height=100)],
        branding_text="MY CHANNEL",
        branding_font=arial if arial.is_file() else None,
        branding_x=20,
        branding_y=20,
        branding_size=32,
        output_path=out,
        segment=ShortSegment(start_seconds=3.0, duration_seconds=5.0),
    )
    await engine.render_short(
        request,
        profile=RenderProfile(name="short-test", width=180, height=320, fps=10,
                              video_codec="libx264", audio_codec="aac",
                              crf=30, preset="ultrafast"),
    )
    probe = await engine.analyze_audio(out)
    assert (probe.width, probe.height) == (180, 320)
    assert 4.0 <= probe.duration_seconds <= 6.5


@pytest.mark.skipif(not FFMPEG_PRESENT, reason="FFmpeg/FFprobe not on PATH")
async def test_integration_extract_audio_and_segment(media_sources):
    engine = FFmpegMediaEngine()
    wav = media_sources["wav"]

    segment = media_sources["tmp"] / "seg.wav"
    await engine.extract_segment(wav, segment, start=2.0, duration=4.0)
    seg_probe = await engine.analyze_audio(segment)
    assert seg_probe.has_audio and not seg_probe.has_video
    assert abs(seg_probe.duration_seconds - 4.0) < 1.0

    # render something, then pull its audio track out
    master = media_sources["tmp"] / "master.mp4"
    await engine.render_master(
        RenderRequest(background=media_sources["bg"], audio=wav, output_path=master),
        profile=TEST_PROFILE,
    )
    audio = media_sources["tmp"] / "extracted.wav"
    await engine.extract_audio(master, audio)
    probe = await engine.analyze_audio(audio)
    assert probe.has_audio and not probe.has_video
    assert probe.sample_rate == 22050
    assert probe.channels == 1
    assert abs(probe.duration_seconds - 15.0) < 2.0


@pytest.mark.skipif(not FFMPEG_PRESENT, reason="FFmpeg/FFprobe not on PATH")
async def test_integration_validation_rejects_bad_expectations(media_sources):
    engine = FFmpegMediaEngine()
    out = media_sources["tmp"] / "master.mp4"
    await engine.render_master(
        RenderRequest(background=media_sources["bg"], audio=media_sources["wav"], output_path=out),
        profile=TEST_PROFILE,
    )
    result = await engine.validate_media(
        out,
        expectations=MediaExpectations(width=9999, height=9999),
    )
    assert result.valid is False
    assert "resolution" in [c.name for c in result.failures]
