"""initial schema: 12 metadata tables

Revision ID: bf717963d7ca
Revises: 
Create Date: 2026-08-10 12:35:25.048110
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf717963d7ca'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('branding_text', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productions_status'), ['status'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('production_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_production_id'), ['production_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_type'), ['type'], unique=False)

    op.create_table('creative_concepts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('production_id', sa.String(length=40), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=False),
    sa.Column('mood', sa.String(length=120), nullable=False),
    sa.Column('theme', sa.String(length=120), nullable=False),
    sa.Column('audience', sa.String(length=120), nullable=True),
    sa.Column('music_direction', sa.Text(), nullable=False),
    sa.Column('visual_direction', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_id', name='uq_creative_concepts_production_id')
    )
    with op.batch_alter_table('creative_concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creative_concepts_production_id'), ['production_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('production_id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_production_id'), ['production_id'], unique=False)

    op.create_table('metadata',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('production_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_id', 'kind', name='uq_metadata_production_kind')
    )
    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metadata_production_id'), ['production_id'], unique=False)

    op.create_table('music_strategies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('production_id', sa.String(length=40), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=False),
    sa.Column('mood', sa.String(length=120), nullable=False),
    sa.Column('bpm_min', sa.Integer(), nullable=False),
    sa.Column('bpm_max', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('structure', sa.String(length=120), nullable=False),
    sa.Column('instruments', sa.JSON(), nullable=False),
    sa.Column('duration_target_minutes', sa.Integer(), nullable=False),
    sa.Column('vocal_policy', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_id', name='uq_music_strategies_production_id')
    )
    with op.batch_alter_table('music_strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_music_strategies_production_id'), ['production_id'], unique=False)

    op.create_table('production_configs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('production_id', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('branding_text', sa.String(length=80), nullable=False),
    sa.Column('branding_position', sa.String(length=32), nullable=False),
    sa.Column('branding_opacity', sa.Float(), nullable=False),
    sa.Column('branding_font_size', sa.Integer(), nullable=False),
    sa.Column('long_form_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('short_form_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('master_width', sa.Integer(), nullable=False),
    sa.Column('master_height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('short_width', sa.Integer(), nullable=False),
    sa.Column('short_height', sa.Integer(), nullable=False),
    sa.Column('visualizer_style', sa.String(length=40), nullable=False),
    sa.Column('provider_profile', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_id', name='uq_production_configs_production_id')
    )
    with op.batch_alter_table('production_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_production_configs_production_id'), ['production_id'], unique=False)

    op.create_table('provider_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('production_id', sa.String(length=40), nullable=False),
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_runs_production_id'), ['production_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_runs_status'), ['status'], unique=False)

    op.create_table('qc_reports',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('production_id', sa.String(length=40), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qc_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qc_reports_production_id'), ['production_id'], unique=False)

    op.create_table('trend_results',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('production_id', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recency', sa.DateTime(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('growth', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('cross_platform', sa.Float(), nullable=True),
    sa.Column('content_fit', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_id', name='uq_trend_results_production_id')
    )
    with op.batch_alter_table('trend_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trend_results_production_id'), ['production_id'], unique=False)

    op.create_table('visual_strategies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('production_id', sa.String(length=40), nullable=False),
    sa.Column('theme', sa.String(length=120), nullable=False),
    sa.Column('environment', sa.String(length=120), nullable=False),
    sa.Column('lighting', sa.String(length=120), nullable=False),
    sa.Column('style', sa.String(length=120), nullable=False),
    sa.Column('color_direction', sa.String(length=120), nullable=False),
    sa.Column('radio_style', sa.String(length=120), nullable=False),
    sa.Column('composition', sa.Text(), nullable=False),
    sa.Column('visualizer_style', sa.String(length=40), nullable=False),
    sa.Column('era', sa.String(length=40), nullable=False),
    sa.Column('palette', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_id', name='uq_visual_strategies_production_id')
    )
    with op.batch_alter_table('visual_strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visual_strategies_production_id'), ['production_id'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('production_id', sa.String(length=40), nullable=False),
    sa.Column('workflow_type', sa.String(length=64), nullable=False),
    sa.Column('task_queue', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_production_id'), ['production_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_production_id'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('visual_strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visual_strategies_production_id'))

    op.drop_table('visual_strategies')
    with op.batch_alter_table('trend_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trend_results_production_id'))

    op.drop_table('trend_results')
    with op.batch_alter_table('qc_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qc_reports_production_id'))

    op.drop_table('qc_reports')
    with op.batch_alter_table('provider_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_runs_status'))
        batch_op.drop_index(batch_op.f('ix_provider_runs_production_id'))

    op.drop_table('provider_runs')
    with op.batch_alter_table('production_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_configs_production_id'))

    op.drop_table('production_configs')
    with op.batch_alter_table('music_strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_music_strategies_production_id'))

    op.drop_table('music_strategies')
    with op.batch_alter_table('metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metadata_production_id'))

    op.drop_table('metadata')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_production_id'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    op.drop_table('events')
    with op.batch_alter_table('creative_concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creative_concepts_production_id'))

    op.drop_table('creative_concepts')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_type'))
        batch_op.drop_index(batch_op.f('ix_assets_status'))
        batch_op.drop_index(batch_op.f('ix_assets_production_id'))

    op.drop_table('assets')
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productions_status'))

    op.drop_table('productions')
    # ### end Alembic commands ###
